### ISSUE TITLE
Failed to load ToDos into Panel every next day. 

### ISSUE THREAD

**Issue by LuzianHahn** [larslockefeer/obsidian-plugin-todo#92]
Hi, 
Thanks for your plugin - it makes my live much easier!

I recently found that after opening obsidian and checking for ToDos in the morning of the next day, the sidebar panel is empty. 
I followed your instruction from #45 to open the developer panel, which indicates an exception. I appended a respective picture here:
![image](https://github.com/user-attachments/assets/a7aca077-2152-4d26-ab3b-608ee573826a)

A restart of obsidian ordinary fixes this. The issues happens on MacOS (Sonoma 14.7.1 - Obsidian 1.7.7) and Ubuntu (Ubuntu 22.04.5 LTS - Obsidian 1.7.6), so I guess it is independent from the OS.

**Comment by larslockefeer** [comment]
Hi @LuzianHahn, apologies for the delay but this should be fixed now 😄

**Comment by LuzianHahn** [comment]
Hey @larslockefeer , thanks for your fix here. Unfortunately it seems, that the issue still persists.
I added the latest release (0.2.8), but I am still running into this:

<img width="910" height="915" alt="Image" src="https://github.com/user-attachments/assets/665b50a6-8e6e-4358-a919-3913e9204161" />

I narrowed down the situation a little. It basically happens, when I open obsidian with a different, right tab, than the TODOs one. Not sure if this is related to me having tasks, which over their due date though.
